export const icons = {
  ARROW_RIGHT: require('../assets/icons/arrow_right/ic_arrow_right.png'),
  PLACEHOLDER_IMAGE: require('../assets/icons/placeholder_image/placeholder_image.png'),
  AFRICA: require('../assets/icons/africa/africa.png'),
  ASIA: require('../assets/icons/asia/asia.png'),
  EUROPE: require('../assets/icons/europe/europe.png'),
  NORTH_AMERICA: require('../assets/icons/north_america/north_america.png'),
  OCEANIA: require('../assets/icons/oceania/oceania.png'),
  SOUTH_AMERICA: require('../assets/icons/south_america/south_america.png'),
  ANTARCTICA: require('../assets/icons/antarctica/antarctica.png'),
  NO_RESULTS: require('../assets/icons/no_results/no_results.png'),
  RANDOM_FLAG: require('../assets/icons/random_flag/random_flag.png'),
  QUESTION_MARK: require('../assets/icons/question_mark/question_mark.png'),
  FIRST_PRIZE: require('../assets/icons/first_prize/first_prize.png'),
  SECOND_PRIZE: require('../assets/icons/second_prize/second_prize.png'),
  THIRD_PRIZE: require('../assets/icons/third_prize/third_prize.png'),
  FLAG_QUIZ: require('../assets/icons/flag_quiz/flag_quiz.png'),
  CAPITAL_QUIZ: require('../assets/icons/capital_quiz/capital_quiz.png'),
  POPULATION_QUIZ: require('../assets/icons/population_quiz/population_quiz.png'),
  WORLD_MAP: require('../assets/icons/world_map/world_map.png'),
  MEMORY_QUIZ: require('../assets/icons/memory/memory.png'),
};
